### ISSUE TITLE
Hackage

### ISSUE THREAD

**Issue by dmjio** [markandrus/twilio-haskell#24]
Have you considered uploading this package to hackage? (Or is it already? I couldn't find it).

**Comment by seagreen** [comment]
I think all twilio-haskell needs to be Hackage compliant is a Setup.hs file: https://github.com/markandrus/twilio-haskell/pull/25

**Comment by markandrus** [comment]
Hey, thanks for your interest! I was going to wait a bit before uploading (until more of the API was covered), but if the package—even in its early state—is useful to you I'll go ahead and upload to Hackage.

**Comment by seagreen** [comment]
Thanks for the quick reply! Once the package can send messages I'd love to have it on Hackage.

**Comment by markandrus** [comment]
twilio-haskell is live on hackage: http://hackage.haskell.org/package/twilio

As additional `Get`/`Post` instances are added, we can bump component C of the version and release as necessary.

**Comment by seagreen** [comment]
This is awesome. :rainbow:

**Comment by dmjio** [comment]
Thanks, and great work.
