### ISSUE TITLE
Add support for sending messages

### ISSUE THREAD

**Issue by seagreen** [markandrus/twilio-haskell#26]
Is this a desired feature? If so I'd be happy to make a PR for it.

**Comment by markandrus** [comment]
@seagreen yes POST operations are desired. We don't really have a pattern for this yet, so if you'd like to start please go ahead.

**Comment by seagreen** [comment]
Sounds great, I'll give it a shot.

**Comment by seagreen** [comment]
Started on in: 37ba00b7f8858459fc688d97583c1b1e632836b7
