### ISSUE TITLE
Consider using Text instead of String

### ISSUE THREAD

**Issue by seagreen** [markandrus/twilio-haskell#29]
If you have a strong preference for String that's totally fine, otherwise I'd be curious to get your thoughts on this.

My impression (I'm a pretty new haskeller) is that it's better to use Text in the data types of new libraries instead of String. New libraries don't have backwards compatibility issues, and Text gives a performance benefit. (In this specific case we're already getting Texts back from aeson as well, so it might also mean less conversion code within the library).

Genuinely curious for your thoughts.

**Comment by markandrus** [comment]
The overloaded string extension makes this fairly painless, so I'm definitely open to it. I think
- First we can consider changing fields on the request/response data types to be `Text`.
- Then we can look at some of the other values (e.g. `Credential` passed in)

It may be useful to extend certain functions to accept `IsString`.

**Comment by seagreen** [comment]
Here's an initial try for you to look at: https://github.com/markandrus/twilio-haskell/pull/30

One of the few things I didn't switch was the arguments to `runTwilio'` and `runTwilioT'`. The `Credentials` they output does use `Text`, but I didn't switch them to take `Text` as an argument because it would have made your README example more ugly. `(fmap T.pack $ getEnv  "ACCOUNT_SID")` just doesn't look the same.

**Comment by markandrus** [comment]
+1 on keeping `runTwilio'` and `runTwilioT'` the same . The rest looks good. Thanks :-)
