### ISSUE TITLE
Bring http-client and time up to the latest version

### ISSUE THREAD

**Issue by seagreen** [markandrus/twilio-haskell#33]
`http-client` and `time` are both behind their latest versions on Hackage. Can we bump them up to the latest major releases (`http-client ==0.4.*` and `time ==1.5.*`) or do you want the old versions to be allowed?

**Comment by markandrus** [comment]
@seagreen i think that is fine. please open a pull request if you have time

**Comment by seagreen** [comment]
Of course:)

**Comment by seagreen** [comment]
https://github.com/markandrus/twilio-haskell/pull/34

**Comment by seagreen** [comment]
Sweet. Will you let me know when you push this to Hackage?

**Comment by markandrus** [comment]
Yes! [Just pushed](https://hackage.haskell.org/package/twilio-0.1.2.0)

**Comment by seagreen** [comment]
Thanks!
