### ISSUE TITLE
Fails on latest version of aeson

### ISSUE THREAD

**Issue by asparks1805** [markandrus/twilio-haskell#39]
##### The error

The build fails when trying to build without a build-depends in the .cabal file = "aeson = 0.9.0.1".  The latest version of aeson is now 0.11.1.4.  The build constraints appear to be too loose.  Error messaging below.
##### Error messaging from shell

 % cabal install --only-dependencies
Resolving dependencies...
Notice: installing into a sandbox located at
/home/aaron/dev/haskell/test5_twilio/.cabal-sandbox
Downloading aeson-0.11.0.0...
Configuring aeson-0.11.0.0...
Building aeson-0.11.0.0...
Installed aeson-0.11.0.0
Downloading twilio-0.1.3.0...
Configuring twilio-0.1.3.0...
Building twilio-0.1.3.0...
Failed to install twilio-0.1.3.0
Build log ( /home/aaron/dev/haskell/test5_twilio/.cabal-sandbox/logs/twilio-0.1.3.0.log ):
Configuring twilio-0.1.3.0...
Building twilio-0.1.3.0...
Preprocessing library twilio-0.1.3.0...

src/Twilio/Internal/Resource.hs:3:13: Warning:
    -XOverlappingInstances is deprecated: instead use per-instance pragmas OVERLAPPING/OVERLAPPABLE/OVERLAPS
[ 1 of 55] Compiling Twilio.Types.PriceUnit ( src/Twilio/Types/PriceUnit.hs, dist/dist-sandbox-422a0fe3/build/Twilio/Types/PriceUnit.o )
[ 2 of 55] Compiling Twilio.Types.List ( src/Twilio/Types/List.hs, dist/dist-sandbox-422a0fe3/build/Twilio/Types/List.o )
[ 3 of 55] Compiling Twilio.Types.ISOCountryCode ( src/Twilio/Types/ISOCountryCode.hs, dist/dist-sandbox-422a0fe3/build/Twilio/Types/ISOCountryCode.o )
[ 4 of 55] Compiling Twilio.Types.Issue ( src/Twilio/Types/Issue.hs, dist/dist-sandbox-422a0fe3/build/Twilio/Types/Issue.o )
[ 5 of 55] Compiling Twilio.Types.Capability ( src/Twilio/Types/Capability.hs, dist/dist-sandbox-422a0fe3/build/Twilio/Types/Capability.o )
[ 6 of 55] Compiling Twilio.Types.AddressRequirement ( src/Twilio/Types/AddressRequirement.hs, dist/dist-sandbox-422a0fe3/build/Twilio/Types/AddressRequirement.o )
[ 7 of 55] Compiling Twilio.Internal.Parser ( src/Twilio/Internal/Parser.hs, dist/dist-sandbox-422a0fe3/build/Twilio/Internal/Parser.o )

src/Twilio/Internal/Parser.hs:5:1: Warning:
    The import of ‘Control.Applicative’ is redundant
      except perhaps to import instances from ‘Control.Applicative’
    To import instances alone, use: import Control.Applicative()
[ 8 of 55] Compiling Twilio.Types.SID ( src/Twilio/Types/SID.hs, dist/dist-sandbox-422a0fe3/build/Twilio/Types/SID.o )
[ 9 of 55] Compiling Twilio.Types.AuthToken ( src/Twilio/Types/AuthToken.hs, dist/dist-sandbox-422a0fe3/build/Twilio/Types/AuthToken.o )
[10 of 55] Compiling Twilio.Internal.Request ( src/Twilio/Internal/Request.hs, dist/dist-sandbox-422a0fe3/build/Twilio/Internal/Request.o )

src/Twilio/Internal/Request.hs:14:1: Warning:
    The import of ‘Control.Exception.Base’ is redundant
      except perhaps to import instances from ‘Control.Exception.Base’
    To import instances alone, use: import Control.Exception.Base()

src/Twilio/Internal/Request.hs:25:1: Warning:
    The import of ‘Network.HTTP.Types.Header’ is redundant
      except perhaps to import instances from ‘Network.HTTP.Types.Header’
    To import instances alone, use: import Network.HTTP.Types.Header()
[11 of 55] Compiling Control.Monad.Twilio ( src/Control/Monad/Twilio.hs, dist/dist-sandbox-422a0fe3/build/Control/Monad/Twilio.o )

src/Control/Monad/Twilio.hs:20:1: Warning:
    The import of ‘Control.Applicative’ is redundant
      except perhaps to import instances from ‘Control.Applicative’
    To import instances alone, use: import Control.Applicative()
[12 of 55] Compiling Twilio.Types     ( src/Twilio/Types.hs, dist/dist-sandbox-422a0fe3/build/Twilio/Types.o )
[13 of 55] Compiling Twilio           ( src/Twilio.hs, dist/dist-sandbox-422a0fe3/build/Twilio.o )
[14 of 55] Compiling Twilio.AvailablePhoneNumber ( src/Twilio/AvailablePhoneNumber.hs, dist/dist-sandbox-422a0fe3/build/Twilio/AvailablePhoneNumber.o )

src/Twilio/AvailablePhoneNumber.hs:50:34:
    Overlapping instances for FromJSON Capabilities
      arising from a use of ‘parseJSON’
    Matching instances:
      instance (Ord a, FromJSON a) =>
               FromJSON (containers-0.5.6.2:Data.Set.Base.Set a)
        -- Defined in ‘aeson-0.11.0.0:Data.Aeson.Types.Instances’
      instance FromJSON Capabilities
        -- Defined at src/Twilio/Types/Capability.hs:21:10
    In the second argument of ‘(>>=)’, namely ‘parseJSON’
    In the second argument of ‘(<_>)’, namely
      ‘(v .: "capabilities" >>= parseJSON)’
    In the expression:
      AvailablePhoneNumber <$> v .: "friendly_name"
      <_> v .: "phone_number"
      <_> (v .: "lata" <&> (=<<) readZ >>= maybeReturn')
      <_> v .: "rate_center"
      <_> (v .: "latitude" <&> (=<<) readZ >>= maybeReturn')
      <_> (v .: "longitude" <&> (=<<) readZ >>= maybeReturn')
      <_> v .: "region"
      <_> (v .: "postal_code" <&> (=<<) readZ >>= maybeReturn')
      <_> v .: "iso_country"
      <_> v .: "address_requirements"
      <*> (v .: "capabilities" >>= parseJSON)
cabal: Error: some packages failed to install:
twilio-0.1.3.0 failed during the building phase. The exception was:
ExitFailure 1

**Comment by markandrus** [comment]
Thanks for the report, @asparks1805. Kicking off a new build now on Travis to confirm.

**Comment by markandrus** [comment]
I read your build log, repro-ed myself, checked [Aeson's changelog](https://hackage.haskell.org/package/aeson-0.11.1.4/changelog), made the change 331f6c50e94ff1b5a79c33b34872f2ff5de29669, and tested locally. It seems to be good. I can update previous releases to rely on `aeson <0.11`. I'll also cut a 0.1.3.1 that requires `aeson >=0.11`.

**Comment by markandrus** [comment]
@asparks1805, I think this is fixed. Can you test 0.1.3.1? It should be available on Hackage now.

**Comment by asparks1805** [comment]
Mark, 

Just tested it. Worked like a charm! Thanks! 

I'm a Haskell noob and still learning. My coding mentor, Eric, also helped me figure out how to build my auth token and secret into the file rather than have it use an environment variable. We're going to make a change to provide that as an option and send a pull request. 

## Thanks for the quick turnaround. 

Aaron

**Comment by markandrus** [comment]
Sounds good, @asparks1805—I look forward to it! Thanks :-)
