### ISSUE TITLE
Deleting Recordings

### ISSUE THREAD

**Issue by cdornan** [markandrus/twilio-haskell#47]
Looking at the Haddocks it looks as if there is no way to delete a `Recording`. I can work the REST API, but I just wanted to check this was the case.

If so, I guess we should have it on the to-do list?

**Comment by markandrus** [comment]
Hi @cdornan,

You're right. This library is kind of a pet project being developed on demand, so we're missing a lot. Delete for Recordings should be pretty straightforward to add, though, I think. See [here](https://github.com/markandrus/twilio-haskell/blob/875b5b5f333838b82d8a3682461c72e4931911e3/src/Twilio/Queue.hs#L63) for how Queues are deleted. It ought to be very similar for [Recordings](https://github.com/markandrus/twilio-haskell/blob/875b5b5f333838b82d8a3682461c72e4931911e3/src/Twilio/Recording.hs#L52).

Thanks,
Mark

**Comment by cdornan** [comment]
Thanks @markandrus &mdash; makes complete sense.

**Comment by markandrus** [comment]
Supported as of 0.2.0.0
