### ISSUE TITLE
Support for Status Callback

### ISSUE THREAD

**Issue by StevenXL** [markandrus/twilio-haskell#63]
Hi - I took a brief look at the library, and I didn't see support for the [Status Callback](https://www.twilio.com/docs/sms/tutorials/how-to-confirm-delivery-ruby) feature. Is it in the library and I just missed it, or is it not yet supported?

**Comment by markandrus** [comment]
Hi, it is not yet implemented.

**Comment by mirko-plowtech** [comment]
Having this field (and others) for Calls it would be really nice.
